backend:
  name: git-gateway
  branch: main
  identity_url: "https://sensational-syrniki-955983.netlify.app/.netlify/identity"
  gateway_url: "https://sensational-syrniki-955983.netlify.app/.netlify/git"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/homepage.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "heroText", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }